<?php ## Меню.

$menu = [
            ["title" => "Главная",
                "link" => "http://vk.com",
                "active" => true,
                "menu_type" => ["top"],
                "position" => ["1", "4"],
            ],
            ["title" => "О нас",
                "link" => "http://vk.com",
                "active" => true,
                "menu_type" => ["left"],
                "position" => ["2", "3"],
            ],
            ["title" => "Новости",
                "link" => "http://vk.com",
                "active" => true,
                "menu_type" => ["top", "left"],
                "position" => ["4","0"],
                "children"=> [
                        [   "title" => "Политика",
                            "link" => "http://vk.com",
                            "active" => true,
                            "menu_type" => ["top", "left", "bottom"],
                            "position" => ["1", "3"],
                        ],
                        [   "title" => "Спорт",
                            "link" => "http://vk.com",
                            "active" => false,
                            "menu_type" => ["top", "bottom"],
                            "position" => ["2", "1"],
                        ],
                        [   "title" => "Финансы",
                            "link" => "http://vk.com",
                            "active" => true,
                            "menu_type" => ["left"],
                            "position" => ["0", "3"],
                        ],
                ]
            ],
            ["title" => "Блог",
                "link" => "http://vk.com",
                "active" => true,
                "menu_type" => ["left", "bottom"],
                "position" => ["0", "1"],
            ],
            ["title" => "Контакты",
                "link" => "http://vk.com",
                "active" => true,
                "menu_type" => ["top", "left", "bottom"],
                "position" => ["3", "2"],
                "children"=> [
                        ["title" => "Адрес",
                            "link" => "http://vk.com",
                            "active" => true,
                            "menu_type" => ["top", "left", "bottom"],
                            "position" => ["2", "3"]
                        ],
                        ["title" => "Телефон",
                            "link" => "http://vk.com",
                            "active" => false,
                            "menu_type" => ["top", "bottom"],
                            "position" => ["1", "4"]
                        ],
                        ["title" => "Мы на карте",
                            "link" => "http://vk.com",
                            "active" => true,
                            "menu_type" => ["top", "left"],
                            "position" => ["0", "2"]
                        ],
                       ]
                ],
    ];
?>