<?php ## Меню.

$menu = [
            ["title" => "Главная",
                "link" => "http://vk.com",
                "active" => "true",
                "menu_type" => ["top"],
                "position" => ["0", "2", "1"],
            ],
            ["title" => "О нас",
                "link" => "http://vk.com",
                "active" => "true",
                "menu_type" => ["left"],
                "position" => ["0", "4", "1"],
            ],
            ["title" => "Новости",
                "link" => "http://vk.com",
                "active" => "true",
                "menu_type" => ["top", "left"],
                "position" => ["1", "2", "3"],
                "children"=> [
                        ["title" => "Политика",
                            "link" => "http://vk.com",
                            "active" => "true",
                            "menu_type" => ["top", "left", "bottom"],
                            "position" => ["1", "3", "2"],
                        ],
                        ["title" => "Спорт",
                            "link" => "http://vk.com",
                            "active" => "true",
                            "menu_type" => ["top", "bottom"],
                            "position" => ["2", "4", "1"],
                        ],
                        ["title" => "Финансы",
                            "link" => "http://vk.com",
                            "active" => "true",
                            "menu_type" => ["top", "left"],
                            "position" => ["1", "3", "4"],
                        ],
                ]
            ],
            ["title" => "Блог",
                "link" => "http://vk.com",
                "active" => "true",
                "menu_type" => ["left", "bottom"],
                "position" => ["0", "2", "1"],
            ],
            ["title" => "Контакты",
                "link" => "http://vk.com",
                "active" => "true",
                "menu_type" => ["top", "left", "bottom"],
                "position" => ["0", "3", "2"],
                "children"=> [
                        ["title" => "Адрес",
                            "link" => "http://vk.com",
                            "active" => "true",
                            "menu_type" => ["top", "left", "bottom"],
                            "position" => ["2", "3", "1"]
                        ],
                        ["title" => "Телефон",
                            "link" => "http://vk.com",
                            "active" => "true",
                            "menu_type" => ["top", "bottom"],
                            "position" => ["0", "4", "1"]
                        ],
                        ["title" => "Мы на карте",
                            "link" => "http://vk.com",
                            "active" => "true",
                            "menu_type" => ["top", "left"],
                            "position" => ["0", "2", "1"]
                        ],
                       ]
                ],
   ];
?>